modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="Legopitstop & Sir_Craftypants Common License"
issueTrackerURL="http://my.issue.tracker/"

[[mods]] #mandatory
modId="morefood" #mandatory

version="1.0.1" #mandatory

displayName="Lot's More Food" #mandatory
updateJSONURL="https://github.com/legopitstop/ModUpdates/raw/master/LotsMoreFood/update.json"
displayURL="https://www.curseforge.com/members/legopitstop/projects"
logoFile="pack.png"
credits="Now available for forge!"
authors="Legopitstop & Sir_Craftypants"
description='''
 This is a port from my datapack! Ever thought that Minecraft needed more food? Then this is your mod! This mod adds more than 50+ Foods. Use to replenish those health and hunger points. Make sure to download the resource pack too.
'''

[[dependencies.morefood]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
